### ISSUE TITLE
Keeping record of model version

### ISSUE THREAD

**Issue by TomiRaatikainen** [UCLALES-SALSA/UCLALES-SALSA#8]
Current NAMELIST based system does not keep track of the source code or the executable (it says "latest" or what ever happens to be in the NAMELIST). Updating NAMELISTs whenever the code changes is not practical, so are there alternatives for the hard-coded version number?

**Comment by JuhaTonttila** [comment]
As long as you use git clone to obtain the model code and the provided runscript, the version number is automatically obtained from the version tags. However, not sure if this works well with the DEV-branch now since the tags are assigned to master. In particular, the value "latest" will occur if you're not using git to download the model.

**Comment by TomiRaatikainen** [comment]
Version is not anymore "latest", but there is an option to add hard-coded information about model versions.
